version: '3'
services:
  api-server:
    image: index.docker.io/jaqb8/ems-backend-api:latest
    ports:
      - '8080:8080'
    networks:
      - ems-backend
    depends_on:
      - mongo
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/keyfile.json
    volumes:
      - ${GCP_KEY_PATH}:/tmp/keys/keyfile.json:ro

  mongo:
    user: $UID
    image: mongo:3.6.21-xenial
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ems
      MONGO_USERNAME: admin
      MONGO_PASSWORD: example
    volumes:
      - ./data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - ems-backend
    command: mongod --auth

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: --interval 30
networks:
  ems-backend:
    driver: bridge
