version: '3'
services:
  api-server:
    image: index.docker.io/jaqb8/ems-backend-api:latest
    ports:
      - '8080:8080'
    networks:
      - ems-backend
    depends_on:
      - mongo
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/keyfile.json
    volumes:
      - ${GCP_KEY_PATH}:/tmp/keys/keyfile.json:ro

  mongo:
    image: mongo:3.6.21-xenial
    environment:
      - MONGODB_INITDB_DATABASE=ems
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - ems-backend

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: --interval 30
volumes:
  mongo-data:
    driver: local
networks:
  ems-backend:
    driver: bridge
